create table if not exists interview_session
(
    date_time      timestamp(6),
    id             bigint generated by default as identity
        primary key,
    candidate_name varchar(255)
);

create table if not exists topic
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table if not exists question
(
    practical       boolean not null,
    id              bigint generated by default as identity
        primary key,
    topic_id        bigint
        constraint fk9h1t7swdq9eej6qf9yxtc8g9w
            references topic,
    difficulty      varchar(255)
        constraint question_difficulty_check
            check ((difficulty)::text = ANY
        ((ARRAY ['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])),
expected_answer varchar(255),
tags            varchar(255),
text            varchar(255)
);

create table if not exists question_attempt
(
    id                   bigint generated by default as identity
        primary key,
    interview_session_id bigint
        constraint fkqja1o3w76vnvcex2c3q6jls5t
            references interview_session,
    question_id          bigint
        constraint fkbby0fyce0hde0y0ty5vs4i4xq
            references question,
    candidate_answer     varchar(255),
    notes                varchar(255),
    result               varchar(255)
        constraint question_attempt_result_check
            check ((result)::text = ANY
        ((ARRAY ['SUCCESS'::character varying, 'PARTIAL'::character varying, 'FAIL'::character varying])::text[]))
    );
